version: "1"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment: 
      - NODE_ENV=production
  mongo:
    image: "mongo"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
    ports:
      - "27017:27017"
networks:
  src_default:
    driver: bridge
